"""
Curated overlay for params in params_used_twice_not_in_dictionary.csv that are not in
tools.sap_unified_param_texts.SAP_UNIFIED_EXPLANATION.

Each parameter maps to (sap_standard, canonical_explanation).
- sap_standard True: DDIC-recognizable SAP field/object name (or common SAP structure column).
- sap_standard False: composite/local/typo/ambiguous label; row should be highlighted yellow in the workbook.

Style: PARAM_DICTIONARY_PROMPT.md / sap_unified_param_texts.py (concise, business-technical, reusable).
"""

from __future__ import annotations

# Non-DDIC / local / typo / presentation-only names → yellow row in Excel.
NON_SAP_STANDARD: frozenset[str] = frozenset(
    {
        "ABS_DMBTR",
        "ACTIVITY",
        "AMOUNT",
        "BALANCE_FR",
        "BALANCE_NORMAL",
        "BALANCE_NORMAL_FR",
        "BALANCE_SPEC",
        "BALANCE_SPEC_FR",
        "BALANCE_TOTAL",
        "BALANCE_TOTAL_FR",
        "BLOCK_DESC",
        "ERR_MSG",
        "ERRORNAME",
        "ERNAM_FIRST",
        "ERNAM_LAST",
        "ERNAM_TEXT",
        "FILE_SIZE",
        "FILE_SIZE_KB",
        "FILE_SIZE_MB",
        "GL_ACC_TXT",
        "NETWR_FR",
        "NETWR_LIPS",
        "NETWR_VBAP",
        "PARKED_IVNOICE",
        "PLANT_DESC",
        "PROCSTAT_DESC",
        "SEVERFLTRD",
        "SEVE_LEVEL",
        "SHIPTO_DESC",
        "TIME_DIFF",
        "TIME_DIFF_UNIT",
        "UMSAV_FR",
        "UPD_DATE",
        "UPD_TIME",
        "USES_32_DO",
        "US_GUI",
        "US_PLUGIN",
        "US_RFC",
        "VALUEORIG",
        "WAERK_FR",
    }
)

# Canonical one-line text for every overlay parameter (including NON_SAP_STANDARD).
CANONICAL: dict[str, str] = {
    # --- Yellow-row (non-DDIC / composite / typo): still carry a short, honest line ---
    "ABS_DMBTR": "Absolute local-currency amount derived from DMBTR-style fields in monitor formulas; not a DDIC field name.",
    "ACTIVITY": "Generic activity label on UI or batch extracts; confirm the underlying table column because it is not a stable SAP element name.",
    "AMOUNT": "Generic monetary amount placeholder in extracts; map to a specific currency amount field (WRBTR, DMBTR, NETWR) for DDIC-safe semantics.",
    "BALANCE_FR": "Presentation bucket for French-language or FR-currency balance columns in reporting output; not a SAP data element.",
    "BALANCE_NORMAL": "Derived 'normal' balance bucket used by the monitor UI to color or group totals; local presentation, not DDIC.",
    "BALANCE_NORMAL_FR": "French or FR-currency variant of the derived normal-balance bucket; local presentation, not DDIC.",
    "BALANCE_SPEC": "Derived 'special stock' balance bucket in grouped balance output; monitor-specific aggregation label.",
    "BALANCE_SPEC_FR": "French or FR-currency variant of the special-stock balance bucket; monitor-specific aggregation label.",
    "BALANCE_TOTAL": "Derived grand-total balance column across buckets in the monitor layout; not a single SAP table field.",
    "BALANCE_TOTAL_FR": "French or FR-currency variant of the derived grand-total balance column; monitor-specific aggregation label.",
    "BLOCK_DESC": "Readable description of a blocking reason paired with a block code; display text, not a standalone DDIC field.",
    "ERNAM_FIRST": "Parsed first-name token from ERNAM-style user fields for readable lists; display derivation, not DDIC.",
    "ERNAM_LAST": "Parsed last-name token from ERNAM-style user fields for readable lists; display derivation, not DDIC.",
    "ERNAM_TEXT": "Formatted user-name text combining ERNAM tokens; display derivation for reporting, not a DDIC element.",
    "ERRORNAME": "Symbolic error or exception name in custom traces; interpret per program; not a universal SAP dictionary name.",
    "ERR_MSG": "Concatenated or formatted error message text for operators; pipeline output, not a single DDIC field.",
    "FILE_SIZE": "Byte size of an attachment or export object in monitoring integrations; technical metric, not SAP business master data.",
    "FILE_SIZE_KB": "File size expressed in kilobytes for readability; technical metric derived from byte counts.",
    "FILE_SIZE_MB": "File size expressed in megabytes for readability; technical metric derived from byte counts.",
    "GL_ACC_TXT": "GL account description text paired with HKONT/SAKNR keys; readable label column, not the account key itself.",
    "NETWR_FR": "Net value shown in French locale or group-currency presentation; reporting column, confirm currency fields on the EI.",
    "NETWR_LIPS": "Net value slice tied to delivery item (LIPS) context in SD extracts; composite label, verify join logic in ABAP.",
    "NETWR_VBAP": "Net value slice tied to sales item (VBAP) context in SD extracts; composite label, verify join logic in ABAP.",
    "PARKED_IVNOICE": "Typo-style label for parked-invoice monitoring; treat as local parameter spelling and align to MIRO/FI parked-doc fields in code.",
    "PLANT_DESC": "Plant name or description text paired with WERKS; readable master-data label, not the plant key field.",
    "PROCSTAT_DESC": "Readable description of purchasing processing status (PROCSTAT); text expansion for reporting output.",
    "SEVERFLTRD": "Custom severe-filter or severity-filter flag in monitor selection; confirm meaning in the EI ABAP (non-DDIC name).",
    "SEVE_LEVEL": "Custom severity level bucket for alert triage; confirm thresholds in the EI ABAP (likely not a DDIC element).",
    "SHIPTO_DESC": "Ship-to party description text on SD outputs; partner master label, not the partner-number key field.",
    "TIME_DIFF": "Elapsed-time delta between two timestamps in the extract; formula metric, not a fixed DDIC field name.",
    "TIME_DIFF_UNIT": "Unit for TIME_DIFF (hours, minutes, days); selector for the delta calculation, not a business master attribute.",
    "UMSAV_FR": "French or FR-currency presentation of UMSAV-style statistical values; reporting column, confirm data element on the EI.",
    "UPD_DATE": "Synonym column for a last-updated calendar date; bind to the real DATS field (UPDDAT/UDATE) in the target structure.",
    "UPD_TIME": "Synonym column for a last-updated time-of-day; bind to the real TIMS field (UPDTIM/UTIME) in the target structure.",
    "USES_32_DO": "Feature flag describing 32-bit data-object usage in a technical collector; integration toggle, not SAP business data.",
    "US_GUI": "Flag counting or filtering GUI-driven executions in mixed RFC/GUI telemetry; monitor-specific, not a DDIC master field.",
    "US_PLUGIN": "Flag for plug-in or extension-hosted calls in custom monitors; confirm in ABAP; not a universal DDIC name.",
    "US_RFC": "Flag counting or filtering RFC-driven executions in mixed telemetry; monitor-specific, not a DDIC master field.",
    "VALUEORIG": "Origin or source-system marker for a value in comparison extracts; semantic varies by EI; confirm in ABAP.",
    "WAERK_FR": "Document currency shown with FR locale or alternate presentation; reporting column, confirm SD currency keys.",
    "ABCIN": "Cycle-counting ABC indicator on plant-material data classifying how often physical inventory runs for the material.",
    "ACTFLG": "Activity or processing-active flag on the captured row marking whether the object is live versus completed or inactive.",
    "AENAM": "Name of the user who last changed the object; paired with change dates for maker accountability in extracts.",
    "AS4POS": "Repository object position/index in version-management listings ordering includes or subobjects in a transportable unit.",
    "AS4USER": "User who last changed a repository object in CTS/SE11-style metadata used for ownership of technical changes.",
    "ATTYP": "Attachment or object-part type discriminator when the structure carries multiple component kinds in one table.",
    "AUSBK": "Supplying company code in intercompany or stock-transfer scenarios identifying the sending legal entity.",
    "AWORG": "Clearing organization or reference-org key on FI clearing lines grouping items posted in one clearing run.",
    "AWREF": "Clearing document reference tying settlement lines to the clearing document that netted open items.",
    "AWSYS": "Logical system of the clearing or reference document used for cross-system reconciliation keys.",
    "AWTYP": "Reference transaction type classifying what business object the clearing reference points to (FI/SD/MM classes).",
    "BANKL": "Bank number key linking payment master to a specific bank account at the house bank in cash management.",
    "BANKS": "Bank country key governing bank-key validation rules and payment formats for the account.",
    "BATXT": "Session header text on batch-input sessions describing purpose or source of the BDC run.",
    "BKLAS": "Valuation class on the material controlling how inventory is valued and which accounts receive postings.",
    "BKTXT": "Document header text on FI/AA documents carrying user narrative for audit and search filters.",
    "BPUMN": "Denominator for price-unit conversion on purchasing conditions translating condition amounts to order quantities.",
    "BPUMZ": "Numerator for price-unit conversion paired with BPUMN to express per-unit purchasing prices correctly.",
    "BRGEW": "Gross weight of the logistics quantity used with GEWEI for shipping and freight calculations.",
    "BSTAR": "Billing-relevance or billing-block style control flag on SD billing-related rows for gating invoice creation.",
    "BSTAT": "Overall billing status on SD billing headers summarizing processing state versus cancellation or completion.",
    "BUCHK": "Posting block or control flag on accounting line items preventing update until blocking reason is cleared.",
    "BUCHM": "Posting method or processing-mode indicator on FI/MM postings describing how values were derived.",
    "BUCHW": "Posting control flag on warehouse or logistics-related FI extensions when inventory and FI are coupled.",
    "BUFLVL": "Buffer hierarchy level in application-server buffer statistics distinguishing global versus local buffer pools.",
    "BUFPOS": "Buffer entry position or sub-index within a buffer snapshot row for technical buffer-dump analysis.",
    "BWKEY": "Valuation area key joining material valuation to plant/company rules for moving-average or standard price.",
    "BWTTY": "Valuation category distinguishing split valuation types such as sales-order stock versus own stock.",
    "CLASID": "Classification internal number referencing a class assignment used in variant configuration and class searches.",
    "CMGST": "Credit-management overall status summarizing credit exposure processing for the business partner or document.",
    "COMSYS": "Communications logical system or partner system id in ALE/IDoc addressing for sender/receiver correlation.",
    "CON_NAME": "Enqueue lock argument name identifying the logical lock object argument in SM12-style lock tables.",
    "CVERSFLG": "Component or active-version flag in repository or switchable development objects marking active definition lines.",
    "DBNAME": "Database name or connection catalog id used when extracts target a specific tenant DB in multi-DB landscapes.",
    "DIWZL": "Duration or lead-time style quantity in PP/shop-floor extracts; confirm element on the EI structure versus I_DLZ naming.",
    "DOMNAM": "Domain name in DDIC describing allowed values for a data element used in technical validation filters.",
    "DSTAT": "Dialog or processing-state code on workflow/work-item style rows describing runtime disposition.",
    "EDATU": "Schedule line date in SD deliveries and sales schedules for availability and transportation planning windows.",
    "EINDT": "Item delivery date on purchasing or delivery structures expressing vendor-promised or requested receipt date.",
    "EKNAM": "Purchasing group description or buyer name text paired with EKGRP for readable procurement ownership lists.",
    "EXTERNIND": "Externally-handled indicator marking whether processing is delegated to an external system or partner.",
    "EXTMODI": "External modification flag on change or transport objects marking edits performed outside the SAP GUI.",
    "EXVKW": "Statistical net value in document currency on SD pricing result rows used for threshold and margin analytics.",
    "FAKSK": "Billing block key on SD billing-relevant objects preventing invoicing until the block is removed.",
    "FDGRV": "Planning group or financial planning group on customer credit profiles for credit-management segmentation.",
    "FIPOS": "Financial budget period or commitment item line on FM/CO budget addresses when funds management is active.",
    "FKIVK": "Intercompany billing variant or billing-type control key on SD billing headers for IC scenarios.",
    "FKIVP": "Intercompany partner or pricing procedure slice on billing data used to split payer and sold-to roles.",
    "FKSTA": "Billing status at header level summarizing whether SD billing is completed, cancelled, or in process.",
    "FKSTK": "Billing status at item level tracking item-level billing completion versus open billing quantities.",
    "FMSTK": "Status of funds management assignment or budgeting state when public-sector FM fields are populated.",
    "FRGST": "Overall release status on purchasing documents summarizing approval strategy progress for PO/PR objects.",
    "FRGSX": "Extended release information or strategy outcome code complementing FRGST on MM release objects.",
    "FROMNUMBER": "Lower bound of a number interval or range-object window used in number-range monitoring extracts.",
    "F_NEW": "Post-change flag or new-version marker in paired-field comparisons distinguishing inserted or refreshed rows.",
    "F_OLD": "Pre-change flag or old-version marker paired with F_NEW for before/after comparisons in change extracts.",
    "GARG": "Enqueue client argument component forming part of the lock key together with GNAME and GCLIENT.",
    "GCLIENT": "Enqueue client field identifying tenant/client dimension on SM12 lock list rows.",
    "GEWEI": "Unit of measure for weight fields such as BRGEW and NTGEW in logistics quantity conversions.",
    "GIDAT": "Goods-issue-related date on delivery or shipment data marking when goods physically left the plant.",
    "GMODE": "Enqueue client mode or lock-mode qualifier controlling shared versus exclusive semantics on the lock row.",
    "GNAME": "Enqueue lock object name identifying the DDIC lock object whose arguments appear on the lock list.",
    "GRPID": "Group id bundling related technical rows such as performance samples or application-log correlation keys.",
    "GTARG": "Technical target key on enqueue/gateway traces pointing to the locked object or RFC target context.",
    "GTCODE": "Transaction code recorded on enqueue or gateway rows tying technical events to user navigation context.",
    "GTHOST": "Gateway host name on RFC/enqueue technical rows identifying the application node serving the request.",
    "GUIVERSION": "SAP GUI patch or version string captured in security or client-audit extracts for client software compliance.",
    "GUNAME": "User name dimension on enqueue/gateway technical rows complementing OS-level batch user fields.",
    "GUSR": "OS or gateway user context executing the technical operation on enqueue or RFC trace rows.",
    "HDALL": "Header-all or aggregate header flag in billing or logistics summaries marking fully-referenced header state.",
    "HDALS": "Alternate header-all or partial-header indicator complementing HDALL in grouped SD/FI extracts.",
    "HKONT": "General ledger account number on FI line items for account-level selection and financial statement mapping.",
    "HOSTADR": "Dotted-decimal IP or host address string on gateway or ICM traces for network-level filtering.",
    "IBLNR": "Physical inventory document number keying inventory count documents in IM warehouse management.",
    "IMPFLG": "Import or inbound-processing flag on integration structures marking rows created by inbound interfaces.",
    "IMPSING": "Single-record import mode indicator controlling whether IDoc or batch interfaces process one item at a time.",
    "INTMODI": "Internal modification or integration-modify flag on technical buffers marking rows adjusted by the collector.",
    "INT_MAXRC": "Maximum internal return code observed in a batch of technical messages summarizing worst-case severity.",
    "IP_ADDRESS": "Normalized IP address string on security or gateway extracts for endpoint-based filtering.",
    "JOBID": "Background job count or job-id component paired with job name keys in CCMS or scheduler extracts.",
    "JOBS_CNT": "Counted jobs metric in aggregated scheduler views expressing how many jobs matched the selection slice.",
    "JOB_ID": "Technical job identifier in external scheduler or cloud ALM bridges mapping SAP jobs to remote ids.",
    "KNTTP": "Account assignment category on purchasing items telling whether stock is project, asset, cost-center, or sales-order.",
    "KNUMV": "Document conditions number tying SD/MM pricing procedure results to header-level condition records.",
    "KOBIS": "Backorder or delivery-relevance indicator on schedule lines showing procurement or delivery tie status.",
    "KODAT": "Date key on capacity or order operations used in PP confirmations for operation-level scheduling.",
    "KOQUA": "Capacity-requirement quantity or quota field in PP detailed scheduling extracts for workload analytics.",
    "KOQUK": "Capacity-requirement unit or key figure complementing KOQUA in shop-floor capacity snapshots.",
    "KOSTA": "Production order header status summarizing whether the order is released, technically completed, or locked.",
    "KOSTK": "Order header user-status or category flag in CO/PP status networks depending on the underlying object.",
    "KOVON": "Valid-from date on condition or agreement records opening the interval where pricing or terms apply.",
    "KURSF": "Exchange rate used to convert foreign-currency amounts to local currency on the posting or pricing row.",
    "KWART": "Condition value class or condition type grouping key in SD/MM pricing analytics when rolled up.",
    "KWERT": "Condition value amount in document currency on pricing result lines for threshold and variance checks.",
    "KZKRS": "Costing variant or product-costing key controlling which costing sheet drives standard cost estimates.",
    "KZWRS": "Statistical currency key on SD/FI analytics rows marking the currency used for statistical value columns.",
    "LAEDA": "Last changed date on archive-relevant or info-structure rows tracking when the aggregate row was refreshed.",
    "LDDAT": "Loading deadline date on deliveries expressing last acceptable date for goods issue or pick/pack completion.",
    "LFART": "Delivery type controlling whether the delivery is outbound, returns, or other logistics scenario category.",
    "LFBNR": "Document flow reference number linking deliveries to preceding documents in SD document-chain analysis.",
    "LFGSA": "Overall delivery status summarizing goods-movement and picking progress at header level.",
    "LFIMG": "Actual delivery quantity in sales units on the delivery item for shipped-versus-ordered variance checks.",
    "LFM1_LOEVM": "Vendor purchasing-data deletion flag (LFM1-LOEVM) marking vendor master purchasing views as logically deleted.",
    "LFM1_SPERM": "Central purchasing block on vendor master (LFM1-SPERR) preventing purchase orders to the supplier.",
    "LFPOS": "Delivery item number identifying each delivery line for joins to SD items and goods-movement records.",
    "LFSTA": "Delivery item status tracking picking, goods-movement, and POD milestones for each delivery line.",
    "LGMNG": "Total delivery-related quantity in base unit used for cumulative delivery versus open-order comparisons.",
    "LOCKFLAG": "Enqueue lock held flag on technical lock rows indicating whether the lock entry is active.",
    "LOGSYS": "Logical system key in ALE identifying sender or receiver systems in distributed integrations.",
    "LSTAT": "Delivery header status summarizing goods-issue, picking, and billing-relevance milestones for the delivery.",
    "LVSTA": "Warehouse management processing status on handling-unit or warehouse-task rows for WM monitoring.",
    "LVSTK": "Warehouse management header status summarizing putaway, picking, or confirmation progress.",
    "MASTER": "Master-data indicator distinguishing template or hierarchy master rows from dependent child records.",
    "MAXRC": "Maximum ABAP return code captured in a batch of messages summarizing worst SY-SUBRC class outcome.",
    "MAXROWS": "Row cap parameter limiting how many lines an extractor returns to protect runtime and export size.",
    "MONAT": "Posting period or calendar month bucket on FI/MM periodic aggregates for period-based reporting.",
    "MONBEW": "Monitoring evaluation or alert-behavior code in /SKN-style monitors classifying how thresholds apply.",
    "MONKAT": "Monitoring category key grouping technical checks under infrastructure, security, or application domains.",
    "MSG": "Short message number or token filter on application status lines paired with message class context.",
    "NBLNR": "Invoice list number grouping multiple billing documents for collective processing in SD billing.",
    "NODATAFLG": "No-data or empty-result flag on extracts signaling that selection yielded no qualifying rows.",
    "NRLEVEL": "Number-range level or interval level in SNRO-style number-range objects for interval health checks.",
    "NRRANGENR": "Number-range object id in SNRO controlling which interval sequence applies to the business numbering.",
    "NTGEW": "Net weight of the shipped or ordered quantity paired with GEWEI for logistics weight checks.",
    "OBJFUNC": "Object function or role code describing how a referenced technical object participates in the process.",
    "OBJ_NAME": "Generic object name key on workflow or technical traces identifying the business object instance.",
    "OWNER": "Owner user or team dimension on transport, job, or monitoring objects for accountability filters.",
    "PACKAGE_INTERVAL": "Sampling cadence for package or collector extracts defining how often metrics are rolled up.",
    "PARGB": "Partner group or partner schema grouping key on SD partner determination for reporting slices.",
    "PDSTA": "MRP or production planning status on order or requirement rows summarizing planning outcome.",
    "PDSTK": "MRP status at header or collective level summarizing whether requirements are covered or critical.",
    "PERIOD": "Generic period bucket key (month/year) on aggregates when fiscal period fields are rolled up for charts.",
    "PKSTA": "Picking status on warehouse-relevant deliveries showing whether pick, pack, and GI steps are complete.",
    "PKSTK": "Picking control status complementing PKSTA when multiple warehouse process types exist.",
    "PLIFZ": "Planned delivery time in days from purchasing info records or schedule lines for lead-time analytics.",
    "PODAT": "Proof-of-delivery or POD confirmation date on deliveries marking customer receipt acknowledgement time.",
    "POSSIBLE_APP": "Possible applications bitmask or category list on gateway/security rows listing allowed handler types.",
    "PREFLG": "Preference or pre-check flag on technical buffers marking rows that passed preliminary validation.",
    "PRESENT_ZERO": "Include-zero or zero-balance presentation flag controlling whether zero metrics appear in output.",
    "PROCESSID": "Technical process identifier on performance or enqueue traces correlating steps within one execution.",
    "PROFILE": "SAP memory profile or buffer-profile name on buffer-statistics extracts grouping counters by profile.",
    "PROF_ASS": "Buffer profile assignment counter or flag describing automatic profile selection in buffer monitoring.",
    "PROF_ASS_T": "Timestamp of last buffer-profile assignment event for staleness checks on automatic tuning.",
    "PROF_DEL": "Buffer profile deletion or rollback counter tracking how often profiles were removed from an instance.",
    "PROF_DEL_T": "Timestamp of last buffer-profile deletion correlating configuration churn with metric spikes.",
    "PROJECT": "Project id or WBS hierarchy key when extracts join CO-PS project data to operational metrics.",
    "PROTOCOL": "Protocol or trace identifier on gateway/RFC logs grouping messages belonging to one conversation.",
    "PSTYP": "Purchasing document item category controlling item behavior, account assignment, and goods-receipt rules.",
    "PWDCHGDATE": "Date of last password change on user master for credential-aging and security policy compliance.",
    "PWDLOCKDATE": "Date when the password was administratively locked marking start of lock-driven login denial.",
    "PWDSETDATE": "Date when the current password was set distinguishing resets from routine rotation events.",
    "RELIK": "Delivery-related invoice list indicator tying deliveries to collective billing or invoice-list runs.",
    "RFC": "Generic RFC protocol filter on gateway traces when the monitor distinguishes RFC from HTTP traffic.",
    "RFC_TYPE": "RFC protocol flavor or destination type qualifier on SMGW traces for narrowing technical classes.",
    "RLWRT": "Cleared amount in local currency on FI clearing items showing how much open item balance was netted.",
    "ROLL": "Roll-in or roll-area memory metric on application-server memory snapshots for dialog heap pressure.",
    "ROUTE": "Shipping route code on deliveries grouping legs and carriers for transportation planning analytics.",
    "RRSTA": "Returns or credit-memo relevance status on SD documents marking follow-up billing scenarios.",
    "SKIPROWS": "Skip-leading-rows parameter on file or table imports controlling how many header rows are ignored.",
    "SLGCONNECTION": "Application-log database connection name in BAL logging for multi-tenant or DBA log routing.",
    "SLGCONNECTIONCOUNTER": "Counter of BAL DB connections opened during a process for technical saturation checks.",
    "SLGDATA": "Application-log payload or data handle reference pointing to longtext or structured log segments.",
    "SLGPASSPORT": "SAP passport or business transaction id propagated through BAL for end-to-end correlation.",
    "SLGROOTCONTEXT": "Root business context string in BAL tying nested messages to a top-level business operation.",
    "SLGTERMIDNEW": "New terminal id recorded on BAL rows when sessions move between front ends or Citrix hosts.",
    "SPE_TMPID": "Temporary or special id bucket on SD/MM extension tables; confirm element on the specific EI structure.",
    "SRCCLI": "Source client in cross-client copies or transports marking where master data originated before replication.",
    "STPRS": "Standard price on material valuation controlling inventory valuation at standard-cost organizations.",
    "STRKORR": "Structure or stack correlation key on short-dump or trace rows grouping related failure events.",
    "SYSNAM": "System name in multi-system landscapes identifying the SAP SID or managed system in telemetry exports.",
    "TARCLI": "Target client for cross-client distribution or transportable changes in CTS-style technical rows.",
    "TARSYSTEM": "Target logical system in ALE distribution identifying where replicated objects are sent.",
    "TDDAT": "Transfer requirement or warehouse transfer date on WM documents for stock-transfer timeliness checks.",
    "TERM": "Terminal id on security or batch-input logs identifying the frontend session that executed the transaction.",
    "TONUMBER": "Upper bound of a numeric interval paired with FROMNUMBER in number-range or counter windows.",
    "TOTAL_MEM_MB": "Total memory megabytes metric on server snapshots for coarse capacity trending versus thresholds.",
    "TOYEAR": "Upper year bound on year-interval selections for archive or fiscal-year window filters.",
    "TPSTATID": "Transport or task-processing status id on CTS objects summarizing modifiable versus released states.",
    "TRACE": "Trace level or trace-enable flag on technical collectors controlling verbosity of gateway or SQL traces.",
    "TRFUNCTION": "Transport function code on CTS requests describing import, export, or repair actions on repository.",
    "TRSTA": "Transport status code on TRKORR-style requests summarizing whether the request is released or protected.",
    "TXZ01": "Short item text on purchasing or SD lines used for free-text filters and readable line descriptions.",
    "UDATE_REPET": "Repeated-change date marker on user-security extracts highlighting recurring password or profile churn.",
    "UEBTK": "Unlimited overdelivery allowed indicator on SD or MM quantity contracts controlling tolerance behavior.",
    "UEBTO": "Overdelivery tolerance percent defining how much quantity overrun is accepted versus the order quantity.",
    "UMODES": "Update-task processing modes bitmask summarizing V1/V2 or similar update kinds on VBHDR extracts.",
    "UMSAV": "Unplanned depreciation or statistical value bucket on asset or CO rows; confirm element on the EI extract.",
    "UPDDT": "Update date synonym on IDoc or change rows mirroring UPDDAT-style last-changed calendar stamps.",
    "USNAD": "User name formatted for display in name-last, name-first order on security or audit listings.",
    "USNAM_HD": "User name on header rows distinguishing header actor fields from item-level user attributes.",
    "USNAZ": "External user or alias string when directory or cloud identities map onto SAP user master keys.",
    "UVPAS": "Open vendor items or FI-item selection flag controlling cleared-versus-open vendor-line retrieval.",
    "UVPIS": "Open customer items or FI-item selection flag controlling cleared-versus-open customer-line retrieval.",
    "VBELP": "Sales document item number alias on extension extracts; typically mirrors POSNR line indexing.",
    "VERPR": "Moving-average price on material valuation rows for inventory value-at-current-price analytics.",
    "VESTK": "Handling-unit or packaging status key on deliveries when HU processing governs shipment structure.",
    "VGBEL": "Preceding SD document number in document flow linking subsequent items to originating sales or delivery.",
    "VGPOS": "Preceding item number paired with VGBEL for precise document-chain joins on SD logistics data.",
    "VGTYP": "Preceding document category qualifying VGBEL semantics across orders, deliveries, and billing types.",
    "VKMZL": "Material determination or listing group key in SD materials assistance; confirm DDIC on the EI view.",
    "VKNZL": "Listing procedure or material listing variant key used in SD material listing configuration.",
    "VKWRA": "Sales value in statistics currency on SD result sets for group-currency margin and revenue analytics.",
    "VKWRT": "Net value in document currency on SD items or headers for commercial threshold checks.",
    "VLSTK": "Delivery-related status at header level summarizing warehouse, picking, and goods-issue milestones.",
    "VOLEH": "Volume unit of measure paired with VOLUM for freight and packing volume calculations.",
    "VOLUM": "Volume quantity of the logistics object used with VOLEH for capacity and load-planning checks.",
    "VRGNG": "Transaction/event key on CO-PA or account-assignment data describing what business movement occurred.",
    "VSTEL": "Shipping point or receiving point controlling loading, transportation planning, and route determination.",
    "VTEXT": "Description text for a configuration object such as status, reason code, or organizational unit.",
    "WADAT": "Goods-issue date planned or actual on deliveries marking when warehouse posts goods movement.",
    "WADAT_IST": "Actual goods-issue date on deliveries distinguishing realized GI from planned WADAT values.",
    "WBSTA": "Goods-movement status at header level summarizing posting state of goods issues and receipts.",
    "WBSTK": "Goods-movement status at item level tracking partial versus complete goods movements per line.",
    "WEMNG": "Goods-receipt quantity on purchasing history or order-related rows for GR-versus-PO variance checks.",
    "WRTBM": "Local-currency amount variant on FI/MM rows; confirm data element; typically mirrors DMBTR semantics.",
    "WRTZL": "Second local-currency or parallel-ledger amount field on FI extracts for parallel valuation views.",
    "XAMEI": "SD item flag controlling whether alternate material entries apply to the sales document line.",
    "XBLNI": "Reference document item flag or cross-item billing indicator on SD/FI rows; confirm on the EI structure.",
    "XBUFI": "Buffer-related indicator on technical performance rows marking buffer involvement in the sample.",
    "XDIFF": "Difference or delta-present flag on comparison extracts highlighting rows where old and new values diverge.",
    "XLOEK": "Deletion flag on purchasing or BOM lines marking items as logically deleted but still visible in history.",
    "XNULL": "Null-value or missing-data indicator on joins marking placeholder rows in outer-join result sets.",
    "XNZAE": "New-item or new-schedule-line flag on SD tables marking lines created in the current change cycle.",
    "XZAEL": "Schedule-line or item-change flag complementing XNZAE on VBAP/VBEP style change slices.",
    "ZEILI": "Item line index within billing or pricing result tables for positional joins on multi-line results.",
}
