"""
Canonical SAP/DDIC-grounded one-line explanations for the attached parameter batch.

Each string is written as a single reusable sentence aligned with standard SAP table/field
semantics (not generic “monitoring prose”). Parenthetical TABLE-FIELD citations are omitted
per style preference; meaning stays DDIC-oriented.
"""

from __future__ import annotations

SAP_CANONICAL_ATTACHED: dict[str, str] = {
    "ERDAT": "Created-on date on the persisted business record—standard master/document creation date axis in SAP tables.",
    "CHANGENR": "Change-document number that uniquely identifies one posted change document for an application object.",
    "TAB_DESC": "Short description of a DDIC table so technical table-name keys are readable in output.",
    "ACT_CHNGNO": "Active change-document number on the business object while change recording is processed—ties rows to the current change document header key.",
    "CHANGE_IND": "Header-level change indicator (insert/update/delete semantics) for the changed application object in change-document processing.",
    "CHANGE_IND_DESC": "Text for the header change-indicator domain—human-readable meaning of CHANGE_IND codes in change analytics.",
    "CHNGIND": "Item-level change indicator on change-document item lines marking insert, update, delete, or key changes per field group.",
    "CHNGIND_DESC": "Text for the item change-indicator domain—readable expansion of CHNGIND values on change item rows.",
    "OBJECTCLAS": "Change-document object class naming which SAP business object type the change log belongs to.",
    "OBJECT_DESC": "Description of the referenced business/change object—readable label beside OBJECTCLAS or generic OBJECT keys.",
    "PLANCHNGNR": "Formal engineering/planning change number referencing a released engineering-change record tied to master updates.",
    "UNIT_NEW": "Unit of measure after change on quantity fields—pairs with NEW_VAL in old/new quantity comparisons on change items.",
    "UNIT_OLD": "Unit of measure before change on quantity fields—pairs with OLD_VAL for before/after quantity analysis.",
    "MESSAGE": "Application message text returned to callers for readable error and status explanation.",
    "OBJECT": "Business object discriminator: may hold authorization object, number-range object, BAL object, or other object id per structure.",
    "AUFNR": "Order number key for internal orders or manufacturing orders—primary CO/PP order identifier in many extracts.",
    "ACTION_DESC": "Description of the recorded user/change action on the change document (custom change-action text elements in this solution).",
    "AGR_FDATE": "Valid-from date of a PFCG role assignment—start of the time window where the user may exercise the role’s authorizations.",
    "AGR_TDATE": "Valid-to date of a PFCG role assignment—end of authorization validity for that user–role pairing.",
    "ARKTX": "Short text for a manufacturing order component or BOM line (material description at order-component level).",
    "AS4DATE": "Repository last-changed date of a DDIC or ABAP object for technical object staleness and transport comparisons.",
    "AS4TIME": "Repository last-changed time paired with the repository last-changed date for precise DDIC object timestamping.",
    "ATTRBT": "Attribute or field name on a change-document attribute line identifying which table attribute was captured in the change slice.",
    "BADAT": "Requisition date expressing when material is required—drives need-by and replenishment timing in MM.",
    "BANKN": "House bank account id linking company code banking data to a specific account at the house bank (payment run context).",
    "BLART": "FI document type classifying accounting documents such as invoices, payments, or general postings.",
    "BPMNG": "Purchase order quantity in the order unit—commercial quantity negotiated on the PO line.",
    "BPRME": "Order unit of measure for BPMNG on the PO item—unit of measure that prices and quantities are expressed in.",
    "BUZEI": "Accounting document line item number uniquely numbering lines within one FI document number.",
    "CHARG": "Batch number identifying a distinct material batch for selection, traceability, and shelf-life logic.",
    "COMP_CODE_DESC": "Company code name or description presenting the legal-entity label beside company-code keys.",
    "COMP_OPERATOR": "Comparison operator used to evaluate thresholds (equal, less-than, greater-than, etc.).",
    "COND": "Open SQL WHERE-condition fragment composing dynamic selection predicates on database reads (parameterized filter clause).",
    "DMBTR_FR": "Amount in company-code currency on the FROM side of a currency conversion or paired-amount comparison (local-currency leg).",
    "ENDDATE": "Background job logical end date bounding the observed job execution interval with ENDTIME.",
    "ENDTIME": "Background job end time paired with ENDDATE to close the execution timestamp window.",
    "EREKZ": "Final invoice indicator on the PO item signaling that invoice completion is expected or locked for the line.",
    "ERFME": "Unit of entry for the posted goods-movement quantity—unit of measure actually entered during goods receipt or issue.",
    "ERFMG": "Goods-movement quantity expressed in the entry unit—operational movement quantity before conversion to base unit of measure.",
    "ERRNO": "Numeric error code from OS, network, or RFC runtime layers complementing MSGNO and message text in technical diagnostics.",
    "ETENR": "Schedule line number splitting a sales item into multiple delivery or availability schedule rows.",
    "FABKL": "Factory calendar id defining working days, holidays, and shift rules for date arithmetic.",
    "FACDATE": "Calendar date interpreted through factory-calendar rules (working-day shifts) for planning and SLA-style day counts.",
    "FKSTO": "Indicator that a billing document is cancelled (billing cancellation document versus normal invoice) in SD billing headers.",
    "FKTYP": "SD billing category or type classifying the billing document’s commercial role (invoice, rebate, etc.).",
    "FRGKZ": "Purchasing release state indicator on requisitions or orders showing whether and how release strategy applies.",
    "GRUND": "Reason code explaining why a movement or posting happened—ties physical or logical events to configured reason keys.",
    "HWAER": "Local currency key of the company code used to interpret amounts in company-code currency.",
    "INCLUDENAME": "ABAP include name narrowing code-object selection (dumps, where-used, include-level maintenance context).",
    "KDATB": "Condition record valid-from date opening the pricing or condition interval.",
    "KDATE": "Condition or agreement validity end date (valid-to) closing pricing master or contract validity.",
    "KDEIN": "Condition pricing unit denominator—per how many units the condition amount applies in pricing scales.",
    "KLMENG": "Cumulative schedule or order quantity in the sales item context—confirmed or requested quantity accumulated on schedules.",
    "KONZS": "Partner group or hierarchy account (customer or vendor grouping key) linking affiliated accounts for reporting.",
    "KOSTL": "Cost center used as primary CO account assignment for postings and budgets.",
    "KSCHL": "Condition type such as base price, discount, or freight controlling SD and MM pricing procedures.",
    "KTOPL": "Chart of accounts governing GL account numbering, groups, and financial statement versions.",
    "KWMENG": "Cumulative order quantity in sales units on the item—commercial ordered quantity for SD lines.",
    "LBKUM": "Valuated stock quantity in movement or enhanced inventory extracts—quantity leg of valuated stock snapshots.",
    "MBLNR": "Material document number key for goods movements and inventory postings.",
    "MJAHR": "Material document fiscal year completing uniqueness of the material document number per company code and year.",
    "MODBE_NAME_FIRST": "User or business partner given name captured with modification events—readable first-name dimension for audit lists.",
    "MODBE_NAME_LAST": "User or business partner family name captured with modification events—readable last-name dimension for audit lists.",
    "MSGNO": "Message number within a message class identifying the specific message line behind SY-MSGNO.",
    "MSGTY": "SAP message type (E/W/I/S/A) governing severity, dialog behavior, and logging of application messages.",
    "MTART": "Material type classifying procurement, production, and valuation behavior of material master records.",
    "NEW_VAL": "New field value after a change—paired with OLD_VAL on change pointers, change documents, or custom audit structures.",
    "OBJNR": "Status-management object number linking orders, notifications, or WBS elements to user and system statuses.",
    "OLD_VAL": "Previous field value before a change—paired with NEW_VAL for before/after forensic comparison.",
    "PARVW": "SD partner function such as sold-to, ship-to, or payer defining partner roles on documents.",
    "PAYER_DESC": "Readable name or description of the payer partner for billing and FI accounts receivable context.",
    "PLPLA": "Production version key selecting a BOM and routing alternative for a material in a plant.",
    "PRCTR": "Profit center used for management accounting segmentation and profitability reporting.",
    "PROCSTAT": "Purchasing document processing state describing lifecycle and processing of MM purchasing objects.",
    "PSTYV": "Sales document item category controlling item behavior, pricing relevance, and delivery rules.",
    "QNAME": "qRFC queue name identifying serialized asynchronous RFC workload.",
    "QRFCFNAM": "Target function module registered for execution from a qRFC queue entry.",
    "QRFCUSER": "SAP user context executing the queued RFC function module (queue worker identity).",
    "REF_FIELD_NAME1": "Primary DDIC reference field name driving dynamic comparisons, conversions, or check-table semantics.",
    "REF_FIELD_NAME2": "Secondary DDIC reference field name paired with REF_FIELD_NAME1 for two-field reference logic.",
    "REQ_CNT": "Required hit count threshold—monitor logic waits until at least this many qualifying rows or events are present.",
    "RESULT_COMP": "Right-hand comparison operand (literal or bound value) evaluated against extracted metrics in alert logic.",
    "RFBSK": "Billing-to-FI transfer status on the SD billing header indicating whether and how invoicing posted to accounting.",
    "SAKTO": "Cost element used in CO postings for primary or secondary cost capture and account assignment.",
    "SALK3": "Total valuated inventory value in company-code currency from material valuation aggregates.",
    "SPERR": "Blocking or lock indicator marking master data or transactions as administratively blocked from use.",
    "STAT": "Status code on a status-managed object—user status, system status, or domain-specific state id depending on object class.",
    "STKZN": "Natural-person indicator on customer or vendor master distinguishing natural persons from legal entities.",
    "SUBOBJECT": "Application-log subobject refining application logging under a main object.",
    "SUBSYSTEM": "Technical subsystem key grouping monitoring collectors for infrastructure scope.",
    "SYHOST": "Application server host at short-dump time for node-specific error trending.",
    "SYUSER": "SAP user active when the short dump occurred for accountability on failure rows.",
    "TABE": "Application-log message-number dimension in this corpus, labeled Message ID, paired with MSGID filtering.",
    "TID": "Transaction id of the SAP LUW or external TID correlating related updates in RFC, qRFC, or trigger chains.",
    "TIME_REF_FLD": "Name of the time field used as the aging anchor—time analogue of DATE_REF_FLD for duration-from-reference logic.",
    "TRKORR": "Transport request or task id in CTS identifying a repository change package.",
    "TRN_BY": "Transaction code filter including only listed transaction codes in transport or change-related extracts (include list).",
    "TRN_EX": "Transaction code exclusion filter removing specific transaction codes from transport or change-related extracts.",
    "TRSTATUS": "Transport request status such as modifiable or released governing CTS workflow.",
    "TXT": "Free-text or message-text line carrying human-readable narrative on the row.",
    "UNAME": "SAP user name on business records—the standard 12-character user id for actor attribution.",
    "USTYP_DESC": "Description of SAP user type (dialog, system, service, communication) for readable security segmentation.",
    "VARIANT": "Report selection variant storing saved selection-screen values for batch or interactive execution.",
    "VGART": "Transaction type on the material document header classifying the inventory posting category.",
    "VPRSV": "Price control indicator S or V choosing standard price versus moving-average inventory valuation.",
    "VRKME": "Sales unit of measure for the material in SD documents—unit for commercial sales quantities.",
    "WEPOS": "Goods-receipt indicator on purchasing history rows marking lines created by goods receipt postings.",
    "WERKS_DESC": "Plant name or description providing readable site context beside plant keys.",
    "WORKING_DAYS": "Count of factory-calendar business days used for SLA aging that excludes non-working dates.",
    "W_VARIANT": "Include-program variant selector for X-includes, choosing saved include parameters.",
    "ZEILE": "Line or item index within a document table—generic positional counter for item arrays.",
    "ZEIT": "Time-of-day field paired with dates for timestamp precision on business or technical records.",
    "ZTERM": "Terms of payment key driving baseline due dates, cash discount periods, and payment rules.",
}
