"""
SAP-grounded unified explanations for Part 1 parameters that appear in ≥2 EI files.

Strings are concise, technical, and aligned with typical SAP table/field semantics
(DDIC, transaction context). They intentionally abstract away per-EI marketing prose.
"""

SAP_UNIFIED_EXPLANATION: dict[str, str] = {
    "ADRNR": "Central address reference (ADRNR / business address) tying a result row to address master (ADRC) for ownership and partner traceability.",
    "BACKDAYS": "Default lookback length in calendar days from the evaluation date when operators omit explicit from/to ranges; in code it is mapped onto the active date axis (often paired with DATE_REF_FLD or the primary DATS selection field).",
    "BTCJOBCNT": "Scheduler job counter (JOBCOUNT / BTCJOBCNT) forming part of the batch job key together with job name on CCMS / work-process aggregate extracts.",
    "BTCJOBNAME": "Scheduler job name (TBTCO-JOBNAME / BTCJOB) used to correlate work-process rows with the owning background job.",
    "CNT": "Cardinality gate after the monitor has built its working set—accept interval for row count, grouped queue depth, or work-process totals depending on the function’s aggregation logic.",
    "CUAPROGRAM": "CUA program name (structure WPTOTINFCP) identifying the transaction / dialog stack behind a work process in SM50/SM66-style totals.",
    "DATE_REF_FLD": "Name of the DATS/TIMS anchor field that receives the implicit BACKDAYS window and drives duration-from-reference logic (`CASE LV_DATE_REF_FLD` pattern in `/SKN` job and security monitors).",
    "DATUM": "Explicit as-of calendar date overriding SY-DATUM for selection windows and aging calculations when the run must not use the batch start day.",
    "DEST": "Logical RFC destination (RFCDEST) or enqueue destination key used to scope remote lock / RFC-based extracts.",
    "DIRECT": "IDoc direction flag from EDIDC-DIRECT (1=outbound, 2=inbound relative to the captured system) for ALE/EDI traffic splits.",
    "DOCNUM": "IDoc number EDIDC-DOCNUM for single-document selection or incident drill-down.",
    "DUMPS_CNT": "Alert band on the counted short-dump rows (ST22/SNAP) returned after PROGRAMNAME/SY filters—distinct from runtime DURATION aging.",
    "DURATION": "Relative-age filter: elapsed interval from the row’s reference timestamp to evaluation time, expressed in DURATION_UNIT (distinct from batch wall-clock DURATION_H/M on job monitors).",
    "DURATION_H": "Batch job gross runtime in hours (end timestamp minus start) for TBTCO / job-list style monitors—not the same semantic as DURATION “age since reference”.",
    "DURATION_M": "Batch job gross runtime in minutes—paired with DURATION_H for sub-hour job runtime SLAs.",
    "DURATION_UNIT": "Unit for DURATION-style aging: domain /SKN/D_SW_DURATION_UNIT (H hours, M minutes, D days, F full-day helper mode where implemented).",
    "DYNPRONR": "Current dynpro (screen) number for batch-input / SHDB-related extracts where UI context matters.",
    "ENDDATE": "Background job logical end date (TBTCO-ENDDATE) for CCMS job list selection.",
    "ENDTIME": "Background job end time paired with ENDDATE to bound the execution window.",
    "ERDAT": "Record creation date (ERDAT) on the underlying business object—generic master/document Created-on axis.",
    "FCODE": "GUI function code (SY-UCOMM class) when monitoring must distinguish user commands inside a transaction.",
    "HOST": "Application server host name (instance level) to restrict extracts to one app node.",
    "IDOCTP": "IDoc basic type / extension family (EDIDC-IDOCTP) for interface-type filtering.",
    "INCLUDENAME": "ABAP include name narrowing short-dump selection (SNAP/SYREPORT lineage) to a code object family.",
    "JOBNAME": "Background job name key (TBTCO-JOBNAME) for SM37/CCMS style job monitors.",
    "LANGU": "Logon / text language (LANGU) controlling SY-LANGU class text reads and user master language slices.",
    "LASTCHNAME": "User who last edited the job definition (TBTCO-LASTCHNAME) for segregation-of-duties on scheduler changes.",
    "MANAGE_IN_UTC": "Framework flag: normalize evaluation timestamps to UTC before comparisons when systems span time zones (cloud/ALM integrations).",
    "MANDT": "SAP client (MANDT) mandatory organizational key on all client-dependent tables.",
    "MAX_RECORDS": "Hard cap on returned rows after selection to protect dialog runtime and export size.",
    "MEMSUM": "Collector memory aggregate (heap/extension) from application-server memory snapshots—used for capacity trending vs. thresholds.",
    "MESSAGE": "SY-/application message number or pattern filter (message class context depends on monitor—typically batch input or status log).",
    "MESTYP": "Single-character SAP message type (S/I/W/E/A) for severity-based filtering of batch-input or log lines.",
    "MSGTXT": "Message short text fragment for fuzzy matching on application status lines.",
    "NO_DATE_RESTRICTION": "Suppresses automatic BACKDAYS→range mapping so date filters rely solely on explicit DATS ranges (common on TBTCO job extracts).",
    "OBJSNS": "Object sensitivity (SO_OBJ_SNS / OBJSNS): SAPoffice visibility class on SOST objects; may be unused placeholder in other extracts—interpret via DDIC element on that EI.",
    "PERIODIC": "Periodic-job indicator (TBTCO-PERIODIC) distinguishing one-off vs. repeating scheduler definitions.",
    "PRIVSUM": "Private-memory slice from the same server snapshot as MEMSUM—private heap pressure indicator.",
    "PROCESS_ICON": "Technical icon key (/SKN/E_SW_STATE_ICON) driving alert visualization independent of STATE_COLOR text buckets.",
    "PROGNAME": "Executable program name linked to the batch job step (report/variant context) for job-list monitors.",
    "PROGRAMNAME": "ABAP program name for short-dump selection (SY-REPORT / SNAP) in dump-count/detail monitors.",
    "QNAME": "Inbound/outbound qRFC queue name (TBQMON/TBQ1 context) for queue depth monitors.",
    "QRFCFNAM": "qRFC target function module name registered for the queue entry.",
    "QRFCUSER": "OS or RFC user context executing the queued function module.",
    "QSTATE": "Queue state flag from qRFC monitoring (ready, running, stopped) per TBQMON semantics.",
    "RCVPOR": "IDoc partner port number of the receiver (EDIDC-RCVPOR) for logical endpoint filtering.",
    "RCVPRN": "IDoc partner number (receiver) EDIDC-RCVPRN (customer number, vendor no., logical system, … depending on partner type).",
    "RCVPRT": "IDoc partner type (KU/LI/LS/…) qualifying RCVPRN decoding rules.",
    "REPID": "IDoc mapping / processing program id (EDI_REPID) or reserved technical id—check DDIC element on the EI; distinguishes inbound FM path for an IDoc type.",
    "RFCDEST": "RFC destination name used for RFC ping/state or generic RFC-based selection (SM59 destination key).",
    "SDLSTRTDT": "Planned start date of the background job (scheduler STRTDATE class field on TBTCO views).",
    "SDLSTRTTM": "Planned start time paired with SDLSTRTDT for exact slot monitoring.",
    "SDLUNAME": "User who scheduled the job (SDLUNAME) for SoD on scheduler actions.",
    "SERIALNR": "Collector serial (COLLSERNR) disambiguating repeated AMS/performance samples on the same host interval.",
    "SERVER": "Application instance / server key for CPU/memory telemetry (RZ10 instance naming, not necessarily RFCDEST).",
    "SNDART": "SAPoffice / IDoc sender object type (document type discriminator on SOST / partner segments).",
    "SNDNO": "Sender object key / number (SAPoffice object id component) for SOST addressing.",
    "SNDPOR": "Sender port (EDIDC-SNDPOR) on IDoc control for partner pipeline filtering.",
    "SNDPRN": "Sender partner number (EDIDC-SNDPRN) with semantics driven by SNDPRT.",
    "SNDPRT": "Sender partner type (KU, LI, LS, …) qualifying SNDPRN.",
    "SNDTP": "Sender partner function / transmission type qualifier where the monitor distinguishes technical vs. logical sender roles.",
    "STARTDATE": "Primary start date axis on the monitored object (document / queue / job—check structure) for windowing; not always identical to STRTDATE on TBTCO extracts.",
    "STARTTIME": "Primary start time paired with STARTDATE for timestamp-level selection.",
    "STATE_COLOR": "Derived traffic-light bucket (/SKN color domain) used for alert triage after status evaluation.",
    "STATE_ICON": "Icon column paired with STATE_COLOR for UI/ALM rendering of severity.",
    "STATUS": "Domain-specific status code filter (IDoc status, queue state, job status—interpret with the EI’s DDIC structure).",
    "STATUS_DESC": "Textual status / message description field for human-readable filtering of result lines.",
    "STAT_ERROR": "IDoc error-state bucket flag (status group) for isolating failed IDocs in status monitors.",
    "STAT_OK": "Successful final-state bucket for IDoc status monitors.",
    "STAT_TRANSIT": "In-transit / intermediate-state bucket for IDocs still being processed.",
    "STAT_WAIT": "Hold / wait-state bucket for IDocs blocked in downstream systems.",
    "SUBTYPE": "IDoc extension / segment subtype (CIMTYPE family) for filtering extension scenarios.",
    "SW_DEST": "Cloud ALM / Side-by-Side extension destination key used to forward execution to the managed landscape.",
    "SYHOST": "Host where the dump occurred (SY-HOST / SNAP host) for node-specific dump counts.",
    "SYUSER": "User context on the dump row (SY-UNAME class) for ownership-based dump trending.",
    "TCODE": "Transaction code filter (SY-TCODE / enqueue GTCODE) narrowing extracts to a functional area.",
    "TYPE": "Technical category flag on the monitored object (message type, object type—resolve via structure column help on that EI).",
    "UDATE": "Last-change date on update-task / VBHDR-derived rows (SM13 family) for recency filtering.",
    "UNAME": "SAP user name (12-char) on the business record—generic user dimension for logs, IDocs, or jobs.",
    "UPDDAT": "Last-changed date on IDoc control (EDIDC-UPDDAT) or analogous change-date axis for integration monitors.",
    "UPDTIM": "Last-changed time paired with UPDDAT for sub-day IDoc / change-pointer windows.",
    "USERID": "Session or batch-input user id filter (BDC log / security audit) distinct from USERNAM display fields on SAPoffice headers.",
    "USERNAM": "Physical sender user name on SAPoffice / SOST objects (actor display) paired with partner numbers.",
    "USER_FLD": "Dynamic Recipient List carrier: technical field name whose values in T_DATA drive alert recipient resolution (/SKN DRL pattern).",
    "UTIME": "Last-change time of day paired with UDATE on update-request / snapshot structures.",
    "VBCLIINFO": "Client-specific update info flag on VBHDR-derived SM13 data—controls client-dependent update behavior in the extract.",
    "VBCLINAME": "Logical update server / client name dimension on VBAPPL_LOG / VBHDR join for SM13 workload grouping.",
    "VBCONTEXT": "Update context (VBMOD/VBHDR context key) classifying V1/V2 update kinds in the captured VBHDR set.",
    "VBLANG": "Logon language recorded on the update header for multilingual update processing.",
    "VBMANDT": "Client key on the update (VBHDR) row—mandatory tenant slice for SM13 monitors.",
    "VBNAME": "Update module / object name dimension identifying which update function created the VB entry.",
    "VBRC": "Update return code from the VB execution (success vs. error) for filtering failed update records.",
    "VBREPORT": "Generating ABAP report / include name on the update record for defect clustering.",
    "VBSTATE": "VB execution state (active, finished, error) on SM13-style update logs.",
    "VBTCODE": "Transaction that enqueued the update (VBHDR-TCODE) for functional-area scoping.",
    "VBUSR": "SAP user who created or owns the update entry—SoD-relevant dimension on SM13 extracts.",
    "VBZONLO": "Local time zone of the update server used when reconciling timestamps vs. UTC.",
    "WP_ACTION": "Dispatcher-reported work process action state (run, hold, stop) on SM50 extracts.",
    "WP_BNAME": "OS-level batch user executing the work process (RZ11 kernel WP context).",
    "WP_CPU": "CPU milliseconds consumed by the work process step for hot-spot detection.",
    "WP_DUMPS": "Count of ABAP short dumps raised inside the work process during the observation window.",
    "WP_ELTIME": "Elapsed (wall) time of the current WP step for long-step detection.",
    "WP_IACTION": "Internal dispatcher action code for the WP state machine (kernel-internal, rarely user-set).",
    "WP_INDEX": "Sequential WP list index in the collector snapshot (technical row key, not business data).",
    "WP_IRESTRT": "Restart / recovery indicator on the WP row after enqueue or resource events.",
    "WP_ISTATUS": "Internal numeric WP status from kernel (dialog, update, batch, spool, … coded values).",
    "WP_ITYPE": "Work process type code (D/B/V/… kernel typology) for SM50 workload classification.",
    "WP_IWAIT": "Wait-state bitmask / code showing semaphore, enqueue, RFC, DB, or idle wait reasons.",
    "WP_MANDT": "Client on the collected WP row when WP data is joined with user sessions.",
    "WP_NO": "Dispatcher work process number on the application instance (SM50 index) unique at snapshot time.",
    "WP_PID": "OS process id of the work process for correlation with OS-level traces.",
    "WP_REPORT": "Currently executing ABAP program / report name in the WP (SY-REPORT class).",
    "WP_RESTART": "Number of automatic WP restarts—signals instability if high.",
    "WP_SEM": "Semaphore / enqueue object name currently blocking the WP (when in lock wait).",
    "WP_SEMSTAT": "Detailed semaphore state text/code from the enqueue client.",
    "WP_SERVER": "Application server name owning the WP (SM51 instance key).",
    "WP_STATUS": "High-level WP status text (running, waiting, stopped) for operator dashboards.",
    "WP_TABLE": "Primary database table currently opened by the WP (VBHDR, etc.) for table-hotspot analysis.",
    "WP_TYP": "Legacy / alternate WP type field mirroring WP_ITYPE in some collectors—same kernel semantics.",
    "WP_WAITINF": "Structured wait-info string from dispatcher (DB, enqueue, RFC target) for root-cause triage.",
    "WP_WAITING": "Flag that the WP is in a non-running wait state (complements WP_IWAIT detail).",
    "WP_WAITTIM": "Cumulative wait milliseconds attributed to the WP step—key for enqueue/RFC delay SLAs.",
}
